name: Trigger auto deployment for fpl-refresh-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ codex/api-fastapi ]
    paths:
    - '**'
    - '.github/workflows/fpl-refresh-app-AutoDeployTrigger-3c19ec23-d916-4353-872f-1d6ca57569d3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FPLREFRESHAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FPLREFRESHAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FPLREFRESHAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: fplrefreshacr001.azurecr.io
          registryUsername: ${{ secrets.FPLREFRESHAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FPLREFRESHAPP_REGISTRY_PASSWORD }}
          containerAppName: fpl-refresh-app
          resourceGroup: fpl-ressource-dev
          imageToBuild: fplrefreshacr001.azurecr.io/fpl-refresh-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


